spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3303/db_quarkus
    username: wb-usuarios
    password: quarkusdb
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.cj.jdbc.Driver

  #Setando padrão de nome da table para seguir o padrão CamelCase, senção informar ele utilizará a convesão de palavras separadas com underscores
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl