spring:
  aws:
    secretsmanager:
      secretName: mysql/secret-teste
      endpoint: http://localhost:4566
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
#definindo padrão de nome da table para seguir o padrão CamelCase, senção informar ele utilizará a convesão de palavras separadas com underscores
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
